name: Build Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download JUCE
      run: |
        git clone --depth 1 --branch 8.0.12 https://github.com/juce-framework/JUCE.git JUCE

    - name: Update JUCE Path
      run: |
        (Get-Content CMakeLists.txt) -replace 'set\(JUCE_PATH.*\)', 'set(JUCE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/JUCE" CACHE PATH "Path to JUCE")' | Set-Content CMakeLists.txt

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Zip Artifacts
      run: Compress-Archive -Path build/CDelay_artefacts/Release/VST3/CDelay.vst3 -DestinationPath CDelay-Windows-VST3.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CDelay-Windows-VST3
        path: CDelay-Windows-VST3.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        tag_name: latest
        name: Latest Build
        files: CDelay-Windows-VST3.zip